# Generated by Django 5.2.1 on 2025-05-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('spent_hours', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ログ',
                'verbose_name_plural': 'ログ',
                'constraints': [models.UniqueConstraint(fields=('task', 'work_date'), name='unique_together'), models.CheckConstraint(condition=models.Q(('spent_hours__gte', 0)), name='worklog_spent_hours__gte_0')],
            },
        ),
    ]
